export const AGENT_SESSION_CODE_BLOCK_CLASSNAME = [
  'max-w-full',
  'overflow-x-hidden',
  'whitespace-pre-wrap',
  'break-words',
  'rounded-lg',
  'border',
  'border-slate-200',
  'bg-slate-100',
  'px-3',
  'py-2',
  'font-mono',
  'text-[11px]',
  'leading-relaxed',
  'text-slate-800',
  'dark:text-slate-100',
  'app-dark-code',
].join(' ');
